- id: ai-review-commit-msg
  name: Check commit message format
  entry: ai-review check-commit
  language: python
  stages: [commit-msg]
  always_run: true

- id: ai-review-code
  name: AI Code Review
  entry: ai-review
  language: python
  stages: [pre-commit]
  pass_filenames: false
